export enum reminderType {
  SUBSCRIBE = 'SUBSCRIBE',
  VACCINATION = 'VACCINATION',
  VETERINAR = 'VETERINAR',
  BATHING = 'BATHING',
  GROOMING = 'GROOMING',
  NAILS = 'NAILS',
  PRIVIVKA = 'PRIVIVKA',
  EARS = 'EARS',
}
